### GET request to example server
POST http://localhost:4000/players
Content-Type: application/json

{
    "assists": "30",
    "dateOfBirth":"1998-03-15",
    "email":"mikaelasdas1234565.lundqvist@floorball.com",
    "goals":"45",
    "jerseyNumber":"11",
    "name": "Jere Karalahti",
    "position":"Defender",
    "team":"Classic Tampere"
}
###